# main task for creating certificate databases
# Example inventory:
#  create_certificate_databases:
#      kdb_id: "{{ item.kdb_id }}"
---
- name: Create certificate databases
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.ssl_certificates.certificate_databases.create
    isamapi:
      kdb_name: "{{ item.kdb_name }}"
      type:  kdb
  with_items: "{{ create_certificate_databases }}"
  notify: Commit Changes