# main task to configure access control policies
# example:
#   access_control_policy_attachments:
#     server: /WebSEAL/default
#     resourceUri: /index.html
#     attachments:
#       - name: test_access_policy
#         type: policy
#     action: set
---
- name: Configure access control policy attachments
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.access_control.policy_attachments.update_attachments
    isamapi: "{{ item }}"
  when: item is defined
  with_items: "{{ access_control_policy_attachments }}"

- name: Publish access control policy attachments
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.access_control.policy_attachments.publish
    isamapi:
      server: "{{ item.server }}"
      resourceUri: "{{ item.resourceUri }}"
  when: item is defined
  with_items: "{{ access_control_policy_attachments }}"
