---
- name: verification
  hosts: all
  become: false
  gather_facts: false

  roles:
    - aac
    - activate_module
    - add_attribute_source
    - add_chain_template
    - add_cluster_node
    - add_federation
    - add_junction
    - add_junction_servers
    - add_mgmtazn_role
    - add_module_chain
    - add_network_ipv4
    - add_oauth_client
    - add_oauth_definition
    - add_partner
    - add_reverseproxy_conf
    - add_runtime_listening_interface
    - add_server_connection_ldap
    - add_server_connection_ws
    - add_static_route
    - add_suffix
    - add_sysaccount_group
    - add_sysaccount_user
    - add_system_alerts_rsyslog
    - add_system_alerts_smtp
    - add_system_alerts_snmp
    - archive_logs
    - authenticate_policy_attachments
    - base
    - bootstrap_local
    - config_dns
    - config_failover_cookie
    - config_fed_dir
    - config_ntp
    - config_policy_attachments
    - config_policyserver
    - config_reverseproxy_aac
    - config_reverseproxy_federation
    - config_reverseproxy_oauth
    - config_snmp_monitoring
    - create_keystore
    - create_mgmt_root_dir
    - create_mgmt_root_file
    - create_reverseproxy
    - create_runtime_template_directories
    - create_snapshot
    - delete_activation
    - delete_mgmt_root_file
    - delete_reverseproxy_conf
    - execute_compare
    - execute_isamcfg
    - execute_pdadmin
    - execute_rp_op
    - export_application_logs
    - export_cluster_sign
    - externalize_hvdb_db2
    - fed
    - first_steps
    - gen_report
    - get_federation
    - get_firmware
    - get_fixpack
    - get_junction_details
    - get_junctions
    - get_reverseproxies
    - import_ca_certs
    - import_client_cert_mapping
    - import_http_transformation
    - import_management_root
    - import_personal_cert
    - import_runtime_template_file
    - import_url_mapping
    - install_firmware
    - install_fixpack
    - install_license
    - load_signer_cert
    - meta
    - sanity_checks
    - search_attribute_source
    - search_mapping_rule
    - set_access_control_policy
    - set_admin_cfg
    - set_admin_pw
    - set_advanced_tuning_parameter
    - set_audit_configuration
    - set_auth_mech
    - set_auth_policy
    - set_cert_replication
    - set_cluster_config
    - set_current_point_of_contact
    - set_federation
    - set_host_records
    - set_junction
    - set_keystore_desc
    - set_ldap_root_pw
    - set_ldap_user_attr
    - set_ldap_user_pw
    - set_mapping_rule
    - set_mgmtazn_role_feature
    - set_network_hostname
    - set_network_ipv4_dhcp
    - set_oauth_client
    - set_oauth_definition
    - set_partner
    - set_reverseproxy_conf
    - set_rsyslog_forwarder
    - set_rsyslog_forwarder_sources
    - set_runtime_replication
    - set_runtime_tuning_parameter
    - set_tcpip_tuning
    - start_config
    - switch_auth
    - update_advanced_configuration
    - update_auth_mech
    - update_management_root
    - update_management_ssl_cert
    - update_network_interface_vlan
    - update_network_ipv4
    - update_point_of_contact
    - update_reverseproxy_conf
    - update_static_route
    - upload_extension
    - upload_ltpa_key
    - upload_mapping_rule
    - web
