# Provide the interface, port, and secure flag for the runtime listening interfaces
# runtime_listening_interfaces:
#   - runtime_listening_interface_interface: local-interface
#     runtime_listening_interface_port: 80
#     runtime_listening_interface_secure: false
#   - runtime_listening_interface_interface: local-interface
#     runtime_listening_interface_port: 443
#     runtime_listening_interface_secure: true

# Comment to be used for creating a snapshot file
add_runtime_listening_interface_comment: "Automated Snapshot Before Adding Runtime Listening Interfaces"
