galaxy_info:
  author: IBM
  description: Role that sets password for embedded ldap admin user
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - password
  - embedded_ldap
  - admin_user
  - set

dependencies:
  - start_config
