galaxy_info:
  author: IBM
  description: Role to configure STS chain templates
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - create
  - sts_chain_template

dependencies:
  - start_config