galaxy_info:
  author: IBM
  description: Role that configure a reverse proxy for AAC (replaces isamcfg)
  company: IBM

  license: Apache

  min_ansible_version: 2.2
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm
  - reverseproxy
  - aac
  - configuration
  - isamcfg

dependencies:
  - start_config
