galaxy_info:
  author: IBM
  description: Role to install a single update
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - install
  - update

dependencies:
  - start_config