galaxy_info:
  author: IBM
  description: Role to create ssl certificate databases
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - create
  - ssl_certificate_databases

dependencies:
  - start_config