# main task to configure access control attributes
# example:
#   access_control_attributes:
#     - name: testAttribute
#       description: attribute for policy decision
#       attributeURI: testAttribute
#       type:
#         policy: true
#         risk: false
#       category: Environment
#       datatype: Boolean
#       predefined: false
#       issuer: ""
#       matcher: 1
#       storageDomain:
#         device: false
#         session: false
#         behavior: false
---
- name: Configure access control attributes
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.attributes.set
    isamapi: "{{ item }}"
  when: item is defined
  with_items: "{{ access_control_attributes }}"
  notify: Commit Changes