- name: "Get the federation partners - {{ get_federation_partners_federation_name }}"
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.fed.partners.get_all
    isamapi:
      federation_name: "{{ get_federation_partners_federation_name }}"
  register: ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    get_federation_partners_ret_obj: "{{ ret_obj['data'] }}"
