- name: Delete management root files/directories
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: "ibmsecurity.isam.web.reverse_proxy.management_root.{{ item.1.type }}.delete"
    isamapi:
      id:             "{{ target }}"
      instance_id:    "{{ item.0.inst_name }}"
  with_items: "{{ item.1.targets }}"
  loop_control:
    loop_var: target
    label:  "(action: [{{ item.1.action }}], type: [{{ item.1.type }}], inst_name:[{{ item.0.inst_name }}], target:[{{ target }}])"
  notify: Commit Changes
