galaxy_info:
  author: IFC
  description: Role to import certificates database (kdb).
  company: IFC

  license: Apache

  min_ansible_version: 2.2
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm
  - kdb
  - certificate

dependencies:
  - start_config
