galaxy_info:
  author: IBM
  description: Role to create a sso key file
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - sso_key

dependencies:
  - start_config