galaxy_info:
  author: IBM
  description: Role to add a module chain to ISAM
  company: IBM

  license: Apache

  min_ansible_version: 2.2
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm
  - sts
  - modulechain
  - add

dependencies:
  - start_config
