# main task to upload jmt files
# Example:
#   jmt_files
#     - filename: uploads/jmt/jmt.conf
---
- name: Upload jmt files
  ibm.isam.isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.junction_mapping.import_file
    isamapi:
      id: "{{ item.file | basename }}"
      filename: "{{ inventory_dir }}/{{ item.file }}"
  with_items: "{{ jmt_files }}"
  notify: Commit Changes
