galaxy_info:
  author: IBM
  description: Role to set host file entries
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - set
  - host_file

dependencies:
  - start_config
