galaxy_info:
  author: IFC
  description: >
    Role to update the management SSL certificate key store.
    The certificate container file must be PKCS12 format (.p12 file) and can contain only
    a single certificate.
  company: IFC

  license: Apache

  min_ansible_version: 2.2
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm
  - snapshot
  - create

dependencies:
  - start_config
